### ISSUE TITLE
LD_RUNPATH_SEARCH_PATHS are sometimes formatted on multiple lines by the sort hook but one line by xcode itself

### ISSUE THREAD

**Issue by noahsark769** [noahsark769/xcodeproj-sort-pre-commit-hook#2]
This makes it annoying to use xcodeproj-sort-pre-commit-hook in larger teams, since some people commit the one-liners and some people commit the multi-liners, leading to large code reviews.

Here's an example project which can be used to reproduce the issue:
[XcodeprojSortTestApp.zip](https://github.com/noahsark769/xcodeproj-sort-pre-commit-hook/files/2182698/XcodeprojSortTestApp.zip)

**Comment by jawwad** [comment]
So just to clarify, Xcode actually formats in on multiple lines, i.e. if you make a slight change to the project file in Xcode, it will reformat the LD_RUNPATH_SEARCH_PATHS line to be on multiple lines.

For some developers the sort hook formats it on one line and for other developers it formats it on multiple lines.

**Comment by thibaudrobelain** [comment]
@noahsark769 this should be closed now :)

**Comment by noahsark769** [comment]
True! Fixed by #3
