### ISSUE TITLE
Executable `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby` not found

### ISSUE THREAD

**Issue by whpanda** [noahsark769/xcodeproj-sort-pre-commit-hook#6]
Executable `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby` not found

**Comment by noahsark769** [comment]
HI @whpanda, sorry it's taken so long to get back to you, didn't realize this issue was open. Could you provide more detail? Is this an error that you get when running the pre-commit hook? What does `ruby --version` print?

**Comment by noahsark769** [comment]
I'm going to close this due to inactivity - feel free to reopen if needed!

**Comment by umbrellait-sergey-kuznetsov** [comment]
I had the same problem after updating to Catalina. I fixed this by updating my .pre-commit-config.yaml file.
Just change rev to the latest value, for me works rev: v1.1.0.

'rvm current' prints ruby-2.6.3 for me.
